# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Ananke Gohugo Theme"
license = "MIT"
licenselink = ""
description = "A Base theme for building full featured Hugo sites"
homepage = ""
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons", "Multilingual", "Stackbit"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.54.0"

[author]
  name = ""
  homepage = ""
